version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: jug-vienna-raffle-postgres
    environment:
      POSTGRES_DB: jugviennaraffle
      POSTGRES_USER: juguser
      POSTGRES_PASSWORD: jugpassword
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U juguser -d jugviennaraffle"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jug-vienna-raffle-app
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/jugviennaraffle
      - SPRING_DATASOURCE_USERNAME=juguser
      - SPRING_DATASOURCE_PASSWORD=jugpassword
      - JUG_VIENNA_CLIENT_SECRET=${JUG_VIENNA_CLIENT_SECRET:-default-dev-value}
    ports:
      - "8080:8080"
